# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Lint
description: Lints terraform-svchost
runs:
  using: composite
  steps:
    - name: Setup Go Environment
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: "go.mod"
        cache: true

    - run: make fmtcheck
      shell: bash

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/8cffdb7d21e5b2b89f163f70c60ac9686c9d6180/install.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANGCILINT_VERSION
      shell: bash
      env:
        GOLANGCILINT_VERSION: v1.64.7

    - run: make lint
      shell: bash
